ERROR 2025-04-07 14:27:03,919 log Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\35196\password\exams\exams\views.py", line 369, in dashboard
    return render(request, 'exams/dashboard.html', context)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\35196\password\exams\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: exams/dashboard.html
ERROR 2025-04-07 14:27:03,925 basehttp "GET /dashboard/ HTTP/1.1" 500 97251
